name: Enforce Branch Naming Policy

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce-branch-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Enforce branch naming policy
        uses: DiRoots-Limited/Di.GitHub.Action.BranchNaming@master
        with:
          policy: |
            hotfix/*:master
            feat/*:develop
            fix/*:develop
            release/*:master
          head_ref: ${{ github.head_ref }}
          base_ref: ${{ github.base_ref }}
